using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MUSEODESCALZOS.Data.Migrations
{
    /// <inheritdoc />
    public partial class tabla : Migration
    {
       protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Verificar si la tabla ya existe
             migrationBuilder.Sql("DROP TABLE IF EXISTS tb_Admin;");
              migrationBuilder.Sql(@"
                    CREATE TABLE tb_Admin (
                        IDAdministrador bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        Nombres text,
                        Apellidos text,
                        FechaNacimiento date NOT NULL,
                        NumDoc text,
                        Distrito text,
                        Provincia text,
                        Direccion text,
                        Imagen text
                    );
                ");


            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tb_Usuario' AND column_name='FechaCreacion') THEN
                        ALTER TABLE tb_Usuario ADD FechaCreacion timestamp with time zone;
                    END IF;
                END $$;
            ");


        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Revertir los cambios
            migrationBuilder.DropColumn(
                name: "FechaCreacion",
                table: "tb_Usuario");

            // Eliminar la tabla tb_Admin si es necesario
            migrationBuilder.Sql("DROP TABLE IF EXISTS tb_Admin;");
        }

    }
}
